name: Generate Snake Animation

on:
  schedule: # Execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: MatheusDiamantino # Substitua pelo seu nome de usuário do GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_ADMIN }} # Adicione o seu token como um secret
